# Generated by Django 3.0.3 on 2020-03-04 10:09

import creative_content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content', models.TextField()),
                ('link', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=15)),
                ('section', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.FileField(upload_to=creative_content.models.user_directory_path)),
            ],
        ),
    ]
