# Generated by Django 3.0.2 on 2020-02-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content', models.TextField()),
                ('link', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=15)),
                ('section', models.IntegerField()),
            ],
        ),
    ]
