# Generated by Django 3.0.3 on 2020-03-01 12:33

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/storage/'), upload_to=documents.models.user_directory_path)),
                ('information', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=10)),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_id', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
