# Generated by Django 3.0.3 on 2020-03-04 10:09

import django.core.files.storage
from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/tanzim/Documents/GitHubRepository/CSE499/PaperlessThesisSubmission/Project Codes/Backend/Test_Website/source/storage/'), upload_to=documents.models.user_directory_path)),
                ('information', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
