# Generated by Django 3.0.3 on 2020-03-14 08:34

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0002_auto_20200308_1840'),
        ('documents', '0005_auto_20200308_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='learners.Group'),
        ),
        migrations.AlterField(
            model_name='document',
            name='paper',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='D:\\Documents\\GitHubRepository\\CSE499\\PaperlessThesisSubmission\\Project Codes\\Backend\\Test_Website\\source\\storage/'), upload_to=documents.models.user_directory_path),
        ),
    ]
