# Generated by Django 3.0.3 on 2020-03-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_auto_20200309_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
