# Generated by Django 3.0.3 on 2020-04-05 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classrooms', '0006_auto_20200322_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(related_name='class_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
