# Generated by Django 3.0.3 on 2020-04-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0009_auto_20200406_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_taken',
        ),
    ]
