# Generated by Django 3.0.3 on 2020-03-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200304_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='upload',
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(default='IDLE', max_length=12),
            preserve_default=False,
        ),
    ]
