# Generated by Django 3.0.3 on 2020-03-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20200304_1704'),
        ('users', '0003_auto_20200304_1054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
