# Generated by Django 3.0.3 on 2020-03-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_educator',
            field=models.BooleanField(default=False),
        ),
    ]
