# Generated by Django 3.0.3 on 2020-03-12 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200312_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification',
            old_name='is_teacher',
            new_name='is_educator',
        ),
    ]
