# Generated by Django 3.0.3 on 2020-03-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200312_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='update',
            field=models.BooleanField(default=False),
        ),
    ]
