# Generated by Django 3.0.3 on 2020-03-12 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_verification_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='update',
        ),
    ]
